# trigger:
# - main

# pool:
#   name: 'Default'
# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'



trigger:
  - main

pool:
  name: 'Default'

variables:
  name: 'test'

stages:
  - stage: Build
    displayName: Building the code
    jobs:
    - job: Build_code
      steps:
        -  script:  |
              docker --version
              az version
              kubectl version --client
        # - task:
            

  - stage: Test
    displayName: Testing the code
    jobs:
    - job: Run_Test
    dependsOn: Build
  - stage: Docker_Build
    displayName: Building the docker aimge
    jobs:
    - job: Build_Image
  - stage: Deploy_to_Dev
    displayName: Deploy the image in the dev
    jobs:
    - job: Deploy_dev
  - stage: Deploy_to_Prod
    displayName: Deploy the image to the prod
    jobs:
    - job: Deploy_prod


