name: Deploy the application
run-name: Deploy application
on:
    push:
        branches:
            -  main
            - develop
    workflow_dispatch:
        
jobs:
    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repo
              uses: actions/checkout@v3
            
            - name: Build the applition
              run: |
                ls
                cat docker-compose.yml
                # dummy artifact 
                echo "Applition is working fine" > build-output.txt
            
            - name: Check the build job
              run: |
                 echo "This job is working"

            - name: Update artifact
              uses: actions/upload-artifact@v3
              with:
                name: build-artifact
                path: build-output.txt


    test:
        name: Testing the job
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - name: test the code
              run: |
                 echo "Testing......."
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: build-artifact
                path: ./artifact
            
            - name: test the code
              run: |
                ls
                ls ./artifact
                cat ./artifact/build-output.txt
                
    deploy_to_dev:
            name: Deply the application to the cluster
            runs-on: ubuntu-latest
            needs: test
            environment: dev
            steps:
                - name: deploy application
                  run: |
                     echo "Deplying applition"
                     echo " This is the secret name : ${{ secrets.ENV_NAME }}"
                     echo " This is the env name : ${{ vars.NAME }}"
    # deploy_to_prod: