name: Deploy the application
run-name: Deploy application
on:
    push:
        branches:
            -  main
            - develop
    workflow_dispatch:
        
jobs:
    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - name: checkout the repo
              uses: actions/checkout@v3
            
            - name: Build the applition
              run: |
                ls
                cat docker-compose.yml
            
            - name: Check the build job
              run: |
                 echo "This job is working"

    test:
        name: Testing the job
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - name: test the code
              run: |
                 echo "Testing......."
                
    deploy_to_dev:
            name: Deply the application to the cluster
            runs-on: ubuntu-latest
            needs: test
            environment: dev
            steps:
                - name: deploy application
                  run: |
                     echo "Deplying applition"
                     echo " This is the env name : ${{ secrets.ENV_NAME }}"
    # deploy_to_prod: